# version:  '3.8'
services:
  php:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./var:/var/www/html/var
    networks:
      - symfony

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - symfony

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blogdb
    ports:
      - "3306:3306"
    networks:
      - symfony

  client:
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  symfony:
    driver: bridge